var1="Só"
var2="trabalho"
var3="sem"
var4="diversão"
var5="faz"
var6="de"
var7="João"
var8="um"
var9="chato"
print(var1+" "+var2+" "+var3+" "+var4+" "+var5+" "+var6+" "+var7+" "+var8+" "+var9+".")
